language: node_js
node_js:
  - '6'

before_install:
- openssl aes-256-cbc -K $encrypted_0d2dcbe7ab0f_key -iv $encrypted_0d2dcbe7ab0f_iv
  -in gcpcred.json.enc -out gcpcred.json -d

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - yarn global add @google-cloud/functions-emulator

